app:
  resource_path: /app/public
  
database:
  host: mysql
  user: user
  password: pass
  database: database
  db: database

ocr:
  url: http://ocr_image-umiocr-1:1224/api/ocr
  options:
    language: models/config_chinese.txt
    cls: true
    limit_side_len: 999999
    parser: none
    format: text

pdfocr:
  url: http://ocr-image:1224
  

task:
  wait_time: 60  # 无任务时等待时间（秒）
  request_interval: 1  # 请求间隔时间（秒）